# cmake/git_version.cmake

if(NOT DEFINED SRC_DIR)
    set(SRC_DIR ${CMAKE_CURRENT_SOURCE_DIR})
endif()

# 1. Fetch the full Commit SHA
execute_process(COMMAND git rev-parse HEAD
        WORKING_DIRECTORY ${SRC_DIR}
        OUTPUT_VARIABLE GIT_SHA
        OUTPUT_STRIP_TRAILING_WHITESPACE)

# 2. Fetch the Branch Name
execute_process(COMMAND git rev-parse --abbrev-ref HEAD
        WORKING_DIRECTORY ${SRC_DIR}
        OUTPUT_VARIABLE GIT_BRANCH
        OUTPUT_STRIP_TRAILING_WHITESPACE)

# 3. Check if the working tree is dirty
execute_process(COMMAND git diff --quiet
        WORKING_DIRECTORY ${SRC_DIR}
        RESULT_VARIABLE GIT_DIRTY_RESULT)

if(GIT_DIRTY_RESULT EQUAL 0)
    set(GIT_DIRTY false)
else()
    set(GIT_DIRTY true)
endif()

# 4. SINGLE git describe call (forces "tag-distance-hash" format)
execute_process(COMMAND git describe --tags --long --always
        WORKING_DIRECTORY ${SRC_DIR}
        OUTPUT_VARIABLE GIT_DESCRIBE
        OUTPUT_STRIP_TRAILING_WHITESPACE)

# 5. Extract the base Tag and the Distance
if(GIT_DESCRIBE MATCHES "^(.*)-([0-9]+)-g[0-9a-f]+$")
    set(GIT_TAG "${CMAKE_MATCH_1}")
    set(TAG_DISTANCE "${CMAKE_MATCH_2}")
else()
    # Fallback if no tags exist yet (GIT_DESCRIBE just returns the hash)
    set(GIT_TAG "${GIT_DESCRIBE}")
    execute_process(COMMAND git rev-list --count HEAD
            WORKING_DIRECTORY ${SRC_DIR}
            OUTPUT_VARIABLE TAG_DISTANCE
            OUTPUT_STRIP_TRAILING_WHITESPACE)
endif()

# 6. Parse Major and Minor versions from the clean GIT_TAG
set(VERSION_MAJ -1)
set(VERSION_MIN -1)
if(GIT_TAG MATCHES "^v([0-9]+)[.]([0-9]+)")
    set(VERSION_MAJ "${CMAKE_MATCH_1}")
    set(VERSION_MIN "${CMAKE_MATCH_2}")
endif()

# 7. Determine Build Number (Pipeline vs Local)
if(DEFINED ENV{GITHUB_RUN_NUMBER})
    set(BUILD_NUMBER $ENV{GITHUB_RUN_NUMBER})
else()
    if(GIT_DIRTY)
        math(EXPR BUILD_NUMBER "${TAG_DISTANCE} + 10000")
    else()
        set(BUILD_NUMBER ${TAG_DISTANCE})
    endif()
endif()

# 8. Generate the header file content
set(VERSION_FILE_CONTENT
"/* AUTO-GENERATED BY CMAKE - DO NOT EDIT */
#pragma once

#include <stdbool.h>

#define GIT_DESCRIBE    \"${GIT_DESCRIBE}\"
#define GIT_TAG         \"${GIT_TAG}\"
#define GIT_SHA         \"${GIT_SHA}\"
#define GIT_BRANCH      \"${GIT_BRANCH}\"
#define GIT_DIRTY       ${GIT_DIRTY}
#define VERSION_MAJ     ${VERSION_MAJ}
#define VERSION_MIN     ${VERSION_MIN}
#define BUILD_NUMBER    ${BUILD_NUMBER}
")

# 9. Only write the file if it has changed to prevent unnecessary recompilations
set(VERSION_FILE_PATH "${SRC_DIR}/generated/version.h")
if(EXISTS ${VERSION_FILE_PATH})
    file(READ ${VERSION_FILE_PATH} EXISTING_CONTENT)
    if(NOT "${EXISTING_CONTENT}" STREQUAL "${VERSION_FILE_CONTENT}")
        file(WRITE ${VERSION_FILE_PATH} "${VERSION_FILE_CONTENT}")
    endif()
else()
    file(WRITE ${VERSION_FILE_PATH} "${VERSION_FILE_CONTENT}")
endif()
